export const DISCOUNT_EVENTS_DATES = Object.freeze({
  CHRISTMAS_DDAY_DISCOUNT_START_DATE: 1,
  CHRISTMAS_DDAY_DISCOUNT_END_DATE: 25,
  WEEKEND_DISCOUNT_DATES: [1, 2, 8, 9, 15, 16, 22, 23, 29, 30],
});
