export const DISCOUNT_UNITS = Object.freeze({
  CHRISTMAS_DDAY_DISCOUNT_UNIT: 100,
  WEEKDAY_DISCOUNT_UNIT: 2023,
  WEEKEND_DISCOUNT_UNIT: 2023,
});

export const DISCOUNT_AMOUNTS = Object.freeze({
  ZERO_DISCOUNT_AMOUNT: 0,
  INITIAL_CHRISTMAS_DDAY_DISCOUNT_AMOUNT: 1000,
  SPECIAL_DISCOUNT_AMOUNT: 1000,
});

export const DISCOUNT_EVENT_CRITERIAS = Object.freeze({
  MIN_TOTAL_ORDER_AMOUNT_FOR_DISCOUNT_EVENT: 10000,
});
