export const DISCOUNT_UNITS = Object.freeze({
  CHRISTMAS_DDAY_DISCOUNT_UNIT: 100,
  WEEKDAY_DISCOUNT_UNIT: 2023,
});

export const ZERO_DISCOUNT_AMOUNT = 0;
export const MIN_TOTAL_ORDER_AMOUNT_FOR_DISCOUNT_EVENT = 10000;
export const INITIAL_CHRISTMAS_DDAY_DISCOUNT_AMOUNT = 1000;
